name: Publish NuGet Package

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install Dependencies
        run: dotnet restore

      - name: Build & Pack
        run: |
          dotnet pack --configuration Release --output ./nupkg

      - name: NuGet Login
        uses: NuGet/login@v1
        id: login
        with:
          user: leenzery

      - name: Publish to NuGet.org
        run: |
          dotnet nuget push ./nupkg/*.nupkg --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
